<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rastreamento.Application\Rastreamento.Application.csproj" />
    <ProjectReference Include="..\Rastreamento.Infrastructure\Rastreamento.Infrastructure.csproj" />
  </ItemGroup>

</Project>
